
backend:
  name: git-gateway
  branch: main

media_folder: "images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "homepage"
    label: "Homepage Content"
    files:
      - label: "Main Page"
        name: "mainpage"
        file: "index.html"
        fields:
          - label: "Language Section Title"
            name: "language"
            widget: "string"
